# If you are using AWS ingress uncomment and get your certificate replace 
# Make change to your dns hostname accordingly
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   name: nginx-demo-pdb-ing
#   annotations:
#     kubernetes.io/ingress.class: "aws-alb"
#     alb.ingress.kubernetes.io/backend-protocol: "HTTP"
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
#     alb.ingress.kubernetes.io/subnets: 'IngressSubnetAz1, IngressSubnetAz2, IngressSubnetAz3'
#     alb.ingress.kubernetes.io/security-groups: iks-intuit-cidr-ingress-tcp-443,iks-intuit-api-gw-ingress-preprod-tcp-443,iks-intuit-app-alb-custom-ingress,iks-intuit-ibp-ingress-tcp-443
#     alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:XXXX:certificate/*****
#     alb.ingress.kubernetes.io/healthcheck-path: "/"
#     external-dns.alpha.kubernetes.io/hostname: nginx-XXX.amazon.com
#     alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-TLS-1-2-2017-01"
# spec:
#   rules:
#   - http:
#       paths:
#       - path: /*
#         backend:
#           serviceName: nginx-demo-app-svc
#           servicePort: 80
#       - path: /
#         backend:
#           serviceName: nginx-demo-app-svc
#           servicePort: 80
---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    chaos.intuit.com/enabled: "true"
  labels:
    app: nginx-demo-app
  name: nginx-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo-app
  template:
    metadata:
      labels:
        app: nginx-demo-app
    spec:
      containers:
      - name: nginx-demo-app
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 4
          successThreshold: 2
          failureThreshold: 3
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nginx-demo-app
            topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx-demo-app
              topologyKey: failure-domain.beta.kubernetes.io/zone
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-demo-app-svc
spec:
  type: NodePort
  selector:
    app: nginx-demo-app
  ports:
  - port: 80
    protocol: TCP
    name: http
---
